const products=[
 {id:'phone',name:'Volt X1 Telefon',cat:'Telefonok',price:50000,icon:'📱',level:1,perk:'A munkák várakozási ideje 15%-kal rövidebb.',cooldown:.15,bonus:0,unlock:[],speedBoost:0},
 {id:'laptop',name:'CrimsonBook Laptop',cat:'Laptopok',price:95000,icon:'💻',level:2,perk:'Feloldja az Adatrögzítés munkát és +5% bevételt ad.',cooldown:0,bonus:.05,unlock:['data'],speedBoost:0},
 {id:'monitor',name:'Redline 27 Monitor',cat:'Kijelzők',price:145000,icon:'🖥️',level:3,perk:'Laptoppal együtt feloldja a Grafikai munkát.',cooldown:0,bonus:.03,unlock:['design'],speedBoost:0},
 {id:'pc',name:'V-Core Gamer PC',cat:'Gaming',price:240000,icon:'🧰',level:4,perk:'Feloldja a Videóvágást és +12% bevételt ad.',cooldown:0,bonus:.12,unlock:['video'],speedBoost:0},
 {id:'headset',name:'Pulse Pro Fejhallgató',cat:'Gaming',price:45000,icon:'🎧',level:4,perk:'+5% bevétel és 7%-kal rövidebb munkafutás.',cooldown:0,bonus:.05,unlock:[],speedBoost:.07},
 {id:'glasses',name:'Vanta XR Szemüveg',cat:'Gaming',price:65000,icon:'🥽',level:4,perk:'Streameléshez szükséges és +15% bevétel, 15%-kal rövidebb munkafutás.',cooldown:0,bonus:.15,unlock:['stream'],speedBoost:.15},
 {id:'mic',name:'CastWave Mikrofon',cat:'Streaming',price:55000,icon:'🎙️',level:4,perk:'Fejhallgatóval és PC-vel feloldja a Streamelést.',cooldown:0,bonus:.03,unlock:['stream'],speedBoost:0},
 {id:'keyboard',name:'Strike RGB Billentyűzet',cat:'Gaming',price:30000,icon:'⌨️',level:3,perk:'+10% bevétel minden munkából.',cooldown:0,bonus:.1,unlock:[],speedBoost:0},
 {id:'mouse',name:'Flux X Gamer Egér',cat:'Gaming',price:25000,icon:'🖱️',level:3,perk:'+5% bevétel minden munkából.',cooldown:0,bonus:.05,unlock:[],speedBoost:0},
 {id:'smart',name:'Nexus Okosközpont',cat:'Okosotthon',price:75000,icon:'🔴',level:5,perk:'+5% bevétel és 5%-kal rövidebb várakozás.',cooldown:.05,bonus:.05,unlock:[],speedBoost:0},
 {id:'chair',name:'Apex Gamer Szék',cat:'Gaming',price:60000,icon:'<svg viewBox="0 0 64 64" width="72" height="72" aria-hidden="true"><g stroke="#d8e0ea" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"><rect x="18" y="8" width="28" height="18" rx="4" fill="#3e434b"/><rect x="14" y="24" width="36" height="11" rx="4" fill="#2b3037"/><rect x="10" y="25" width="4" height="12" rx="2" fill="#2b3037"/><rect x="50" y="25" width="4" height="12" rx="2" fill="#2b3037"/><path d="M31 32V46" stroke="#c8d1db" stroke-width="2.2"/><path d="M22 34H42" stroke="#8e99a6"/><path d="M23 38H41" stroke="#8e99a6"/><path d="M20 46H44" stroke="#313840" stroke-width="2.5"/><path d="M26 46L22 54" stroke="#b4bec9"/><path d="M38 46L42 54" stroke="#b4bec9"/><g fill="#111217" stroke="#d8e0ea" stroke-width="1.1"><circle cx="14" cy="54" r="3.8"/><circle cx="22" cy="54" r="3.8"/><circle cx="42" cy="54" r="3.8"/><circle cx="50" cy="54" r="3.8"/></g><g fill="#d8e0ea"><circle cx="14" cy="54" r="1.6"/><circle cx="22" cy="54" r="1.6"/><circle cx="42" cy="54" r="1.6"/><circle cx="50" cy="54" r="1.6"/></g></g></svg>',level:2,perk:'Munkák futási ideje 20%-kal rövidebb.',cooldown:0,bonus:0,unlock:[],speedBoost:.2}
 ,{id:'consoleStation',name:'ConsoleCore tesztállomás',cat:'Gaming technológia',price:310000,icon:'🎮',level:10,perk:'Feloldja a konzolszerviz-megbízásokat és a konzolműhelyt.',cooldown:0,bonus:.04,unlock:['consoleService'],speedBoost:.04}
 ,{id:'vrToolkit',name:'Vanta VR kalibrátor',cat:'Gaming technológia',price:360000,icon:'🥽',level:10,perk:'Feloldja a VR-kalibrálási munkát és a VR-műhelyt.',cooldown:0,bonus:.05,unlock:['vrService'],speedBoost:.05}
 ,{id:'racingRig',name:'Apex kormánytesztelő',cat:'Gaming technológia',price:285000,icon:'🏎️',level:10,perk:'Feloldja a szimulátor-szervizt és a kormány javítását.',cooldown:0,bonus:.04,unlock:['racingService'],speedBoost:.04}
 ,{id:'controller',name:'Pulse X kontroller',cat:'Gaming technológia',price:85000,icon:'🕹️',level:8,perk:'+5% XP a haladó gaming munkákból.',cooldown:0,bonus:0,unlock:[],speedBoost:0,xpBoost:.05}
];
const jobs=[
 {id:'survey',name:'Online kérdőív',icon:'▦',reward:2000,xp:12,seconds:6,desc:'Gyors piackutatási feladat.',requires:[]},
 {id:'data',name:'Adatrögzítés',icon:'⌨',reward:4000,xp:22,seconds:10,desc:'Digitális adatok rendszerezése.',requires:['laptop']},
 {id:'design',name:'Grafikai munka',icon:'◆',reward:8000,xp:34,seconds:15,desc:'Készíts futurisztikus kampánygrafikát.',requires:['laptop','monitor']},
 {id:'video',name:'Videóvágás',icon:'▶',reward:12000,xp:48,seconds:20,desc:'Vágj össze egy technológiai bemutatót.',requires:['pc','monitor','keyboard','mouse']},
 {id:'stream',name:'Élő stream',icon:'●',reward:15000,xp:60,seconds:25,desc:'Közvetíts egy virtuális tech eseményt.',requires:['pc','headset','glasses','mic','smart'],level:5},
 {id:'consoleService',name:'Konzol rendszerellenőrzés',icon:'🎮',reward:26000,xp:82,seconds:38,desc:'Tesztelj és kalibrálj egy felújított konzolt.',requires:['consoleStation','controller'],level:10},
 {id:'vrService',name:'VR optikai kalibrálás',icon:'🥽',reward:34000,xp:96,seconds:46,desc:'Hangold össze a kijelzőt és a mozgásérzékelőket.',requires:['vrToolkit','glasses'],level:10},
 {id:'racingService',name:'Szimulátor beállítás',icon:'🏁',reward:30000,xp:90,seconds:42,desc:'Kalibráld a kormányt, pedálokat és visszacsatolást.',requires:['racingRig','pc'],level:10}
];
const translations={
  hu:{
    storeMarketEyebrow:'BOLTI LICITEK // MARKET',storeMarketTitle:'Érkező ajánlatok',storeMarketSubtitle:'Az elkészült termékekre változó, nyereséges licitek érkeznek.',
    openWorkshop:'Műhely megnyitása',levelsLabel:'SZINT',systemsLabel:'JÁTÉKRENDSZER',progressLabel:'FEJLŐDÉS',launchEarn:'KERESS KREDITEKET',launchJobs:'Vállalj munkát',launchRepair:'JAVÍTS ÉS ÉPÍTS',launchWorkshop:'Irány a műhely',launchReward:'INGYENES JUTALOM',launchWheel:'Pörgesd meg',
    navShop:'Áruház',navJobs:'Munkák',navWorkshop:'Műhely',navWheel:'Tech bónusz',navTeam:'Csapat',navStore:'Üzlet',navEquipment:'Felszerelésem',navHistory:'Előzmények',credit:'KREDIT',cart:'Kosár',playerProfile:'JÁTÉKOSPROFIL',xpLabel:'Tapasztalat',activeBonus:'Aktív bónusz',systemOnline:'SYSTEM ONLINE // 01',startWorking:'Kezdj el dolgozni',equipmentMarket:'FELSZERELÉS-PIAC',availableTech:'Elérhető technológia',searchPlaceholder:'Termék keresése…',careerCenter:'KARRIERKÖZPONT',chooseTask:'Válassz megbízást',jobsSubtitle:'A jobb felszerelés új munkákat és nagyobb jutalmat nyit meg.',serviceTrade:'SZERVIZ & KERESKEDÉS',workshopTitle:'Újítsd fel. Építsd meg. Add el.',workshopSubtitle:'Vegyél hibás eszközt, diagnosztizáld, vásárolj alkatrészt, majd értékesítsd haszonnal.',inventory:'INVENTORY',myEquipment:'Felszerelésem',equipmentSubtitle:'A megvásárolt eszközeid és aktív bónuszaid.',historyEyebrow:'RENDSZERNAPLÓ',historyTitle:'Tranzakciók',historySubtitle:'Minden megszerzett és elköltött kredit egy helyen.',cartEyebrow:'VIRTUÁLIS KOSÁR',cartTitle:'Kiválasztott eszközök',cartTotalLabel:'Összesen',checkoutButton:'Vásárlás véglegesítése',checkoutNote:'Ez kizárólag játékbeli kredit, valódi fizetés nem történik.',diagnosticTerminal:'DIAGNOSZTIKAI TERMINÁL',diagnosticTitle:'Gyorsdiagnosztika',diagnosticPrompt:'Teljesítsd az egyszeri diagnosztikai feladatot.',resetButton:'Játék újrakezdése',heroTitle:'ÉPÍTSD FEL A<br><em>TECH BIRODALMAD</em>',heroText:'Dolgozz, szerezz kreditet, fejleszd a felszerelésed és oldj fel magasabb szintű megbízásokat.',activeEffect:'AKTÍV HATÁS',emptyProducts:'Nincs ilyen termék a rendszerben.',emptyEquipmentTitle:'Még nincs felszerelésed',emptyEquipmentText:'Vásárolj eszközt az Áruházban, hogy új munkákat oldj fel.',ownedState:'Megvéve',lockedState:'Zárolva',inCartState:'Kosárban',addToCart:'Kosárba',emptyHistory:'Még nincs tranzakció.',emptyCart:'A kosarad üres.',jobReward:'Jutalom:',jobReady:'Felszerelés készen',jobNeeds:'Szükséges:',jobNone:'nincs',jobWait:'Várj',jobStart:'Munka indítása',jobLocked:'Zárolva',jobSeconds:'mp',jobFinished:'{{name}} kész: +{{reward}} kredit',levelUp:'Szintlépés! Elérted a(z) {{level}}. szintet.',confirmReset:'Biztosan újrakezded? Minden játékbeli eredmény törlődik.',resetDone:'A játék újraindult.',addToCartToast:'Termék a kosárba került.',checkoutEmpty:'A kosarad üres.',checkoutMissing:'Még {{amount}} kredit hiányzik.',checkoutSuccess:'Vásárlás sikeres — új képességek aktiválva!',emptyCartTotal:'0 kredit',noTimeLimit:'Nincs időlimit',languageSwitchedHu:'Nyelv váltva magyarra',languageSwitchedEn:'Language switched to English',typingPlaceholder:'Gépelj ide…',cartTotalText:'{{amount}} kredit',cartTotalLabelShort:'kredit',
    products:{
      phone:{name:'Volt X1 Telefon',cat:'Telefonok',perk:'A munkák várakozási ideje 15%-kal rövidebb.'},
      laptop:{name:'CrimsonBook Laptop',cat:'Laptopok',perk:'Feloldja az Adatrögzítés munkát és +5% bevételt ad.'},
      monitor:{name:'Redline 27 Monitor',cat:'Kijelzők',perk:'Laptoppal együtt feloldja a Grafikai munkát.'},
      pc:{name:'V-Core Gamer PC',cat:'Gaming',perk:'Feloldja a Videóvágást és +12% bevételt ad.'},
      headset:{name:'Pulse Pro Fejhallgató',cat:'Gaming',perk:'+5% bevétel és 7%-kal rövidebb munkafutás.'},
      glasses:{name:'Vanta XR Szemüveg',cat:'Gaming',perk:'Streameléshez szükséges és +15% bevétel, 15%-kal rövidebb munkafutás.'},
      mic:{name:'CastWave Mikrofon',cat:'Streaming',perk:'Fejhallgatóval és PC-vel feloldja a Streamelést.'},
      keyboard:{name:'Strike RGB Billentyűzet',cat:'Gaming',perk:'+10% bevétel minden munkából.'},
      mouse:{name:'Flux X Gamer Egér',cat:'Gaming',perk:'+5% bevétel minden munkából.'},
      smart:{name:'Nexus Okosközpont',cat:'Okosotthon',perk:'+5% bevétel és 5%-kal rövidebb várakozás.'},
      chair:{name:'Apex Gamer Szék',cat:'Gaming',perk:'Munkák futási ideje 20%-kal rövidebb.'},
      consoleStation:{name:'ConsoleCore tesztállomás',cat:'Gaming technológia',perk:'Feloldja a konzolszerviz-megbízásokat és a konzolműhelyt.'},
      vrToolkit:{name:'Vanta VR kalibrátor',cat:'Gaming technológia',perk:'Feloldja a VR-kalibrálási munkát és a VR-műhelyt.'},
      racingRig:{name:'Apex kormánytesztelő',cat:'Gaming technológia',perk:'Feloldja a szimulátor-szervizt és a kormány javítását.'},
      controller:{name:'Pulse X kontroller',cat:'Gaming technológia',perk:'+5% XP a haladó gaming munkákból.'}
    },
    jobs:{
      survey:{name:'Online kérdőív',desc:'Gyors piackutatási feladat.'},
      data:{name:'Adatrögzítés',desc:'Digitális adatok rendszerezése.'},
      design:{name:'Grafikai munka',desc:'Készíts futurisztikus kampánygrafikát.'},
      video:{name:'Videóvágás',desc:'Vágj össze egy technológiai bemutatót.'},
      stream:{name:'Élő stream',desc:'Közvetíts egy virtuális tech eseményt.'},
      consoleService:{name:'Konzol rendszerellenőrzés',desc:'Tesztelj és kalibrálj egy felújított konzolt.'},
      vrService:{name:'VR optikai kalibrálás',desc:'Hangold össze a kijelzőt és a mozgásérzékelőket.'},
      racingService:{name:'Szimulátor beállítás',desc:'Kalibráld a kormányt, pedálokat és visszacsatolást.'}
    }
  },
  en:{
    storeMarketEyebrow:'STORE BIDS // MARKET',storeMarketTitle:'Incoming offers',storeMarketSubtitle:'Finished devices receive changing, profitable bids.',
    openWorkshop:'Open workshop',levelsLabel:'LEVELS',systemsLabel:'GAME SYSTEMS',progressLabel:'PROGRESSION',launchEarn:'EARN CREDITS',launchJobs:'Take a job',launchRepair:'REPAIR AND BUILD',launchWorkshop:'Enter workshop',launchReward:'FREE REWARD',launchWheel:'Claim bonus',
    navShop:'Shop',navJobs:'Jobs',navWorkshop:'Workshop',navWheel:'Tech bonus',navTeam:'Team',navStore:'Store',navEquipment:'My Gear',navHistory:'History',credit:'CREDIT',cart:'Cart',playerProfile:'PLAYER PROFILE',xpLabel:'Experience',activeBonus:'Active bonus',systemOnline:'SYSTEM ONLINE // 01',startWorking:'Start working',equipmentMarket:'EQUIPMENT MARKET',availableTech:'Available technology',searchPlaceholder:'Search products…',careerCenter:'CAREER CENTER',chooseTask:'Choose a job',jobsSubtitle:'Better equipment unlocks more jobs and higher rewards.',serviceTrade:'SERVICE & TRADE',workshopTitle:'Restore. Build. Sell.',workshopSubtitle:'Buy faulty devices, diagnose them, source parts, and sell for profit.',inventory:'INVENTORY',myEquipment:'My equipment',equipmentSubtitle:'Your owned devices and active bonuses.',historyEyebrow:'SYSTEM LOG',historyTitle:'Transactions',historySubtitle:'All earned and spent credits in one place.',cartEyebrow:'VIRTUAL CART',cartTitle:'Selected devices',cartTotalLabel:'Total',checkoutButton:'Complete purchase',checkoutNote:'This is only in-game credit; no real payment is required.',diagnosticTerminal:'DIAGNOSTIC TERMINAL',diagnosticTitle:'Quick diagnosis',diagnosticPrompt:'Complete the one-time diagnostic task.',resetButton:'Restart game',heroTitle:'BUILD YOUR<br><em>TECH EMPIRE</em>',heroText:'Work, earn credits, upgrade your gear, and unlock higher-tier missions.',activeEffect:'ACTIVE EFFECT',emptyProducts:'No such product exists in the system.',emptyEquipmentTitle:'You have no equipment yet',emptyEquipmentText:'Buy gear in the Shop to unlock new jobs.',ownedState:'Owned',lockedState:'Locked',inCartState:'In cart',addToCart:'Add to cart',emptyHistory:'No transactions yet.',emptyCart:'Your cart is empty.',jobReward:'Reward:',jobReady:'Equipment ready',jobNeeds:'Needs:',jobNone:'none',jobStart:'Start job',jobLocked:'Locked',jobWait:'Wait',jobSeconds:'sec',jobFinished:'{{name}} ready: +{{reward}} credit',levelUp:'Level up! You reached level {{level}}.',confirmReset:'Are you sure you want to restart? All game progress will be deleted.',resetDone:'The game has restarted.',addToCartToast:'Product added to cart.',checkoutEmpty:'Your cart is empty.',checkoutMissing:'You are missing {{amount}} credit.',checkoutSuccess:'Purchase successful — new abilities activated!',emptyCartTotal:'0 credit',noTimeLimit:'No time limit',languageSwitchedHu:'Nyelv váltva magyarra',languageSwitchedEn:'Language switched to English',typingPlaceholder:'Type here…',cartTotalText:'{{amount}} credit',cartTotalLabelShort:'credit',
    products:{
      phone:{name:'Volt X1 Phone',cat:'Phones',perk:'Work wait times are 15% shorter.'},
      laptop:{name:'CrimsonBook Laptop',cat:'Laptops',perk:'Unlocks the Data Entry job and grants +5% revenue.'},
      monitor:{name:'Redline 27 Monitor',cat:'Displays',perk:'Unlocks the Graphic Design job when paired with a laptop.'},
      pc:{name:'V-Core Gamer PC',cat:'Gaming',perk:'Unlocks Video Editing and grants +12% revenue.'},
      headset:{name:'Pulse Pro Headset',cat:'Gaming',perk:'+5% revenue and 7% faster job completion.'},
      glasses:{name:'Vanta XR Glasses',cat:'Gaming',perk:'Required for streaming and grants +15% revenue and 15% faster job completion.'},
      mic:{name:'CastWave Microphone',cat:'Streaming',perk:'Unlocks Streaming when paired with a headset and PC.'},
      keyboard:{name:'Strike RGB Keyboard',cat:'Gaming',perk:'+10% revenue from every job.'},
      mouse:{name:'Flux X Gaming Mouse',cat:'Gaming',perk:'+5% revenue from every job.'},
      smart:{name:'Nexus Smart Hub',cat:'Smart Home',perk:'+5% revenue and 5% shorter wait times.'},
      chair:{name:'Apex Gamer Chair',cat:'Gaming',perk:'Jobs finish 20% faster.'},
      consoleStation:{name:'ConsoleCore Test Station',cat:'Gaming Technology',perk:'Unlocks console service jobs and the console workshop.'},
      vrToolkit:{name:'Vanta VR Calibrator',cat:'Gaming Technology',perk:'Unlocks VR calibration jobs and the VR workshop.'},
      racingRig:{name:'Apex Racing Wheel Tester',cat:'Gaming Technology',perk:'Unlocks simulator service jobs and racing wheel repairs.'},
      controller:{name:'Pulse X Controller',cat:'Gaming Technology',perk:'Grants +5% XP from advanced gaming jobs.'}
    },
    jobs:{
      survey:{name:'Online survey',desc:'Quick market research task.'},
      data:{name:'Data entry',desc:'Organize digital records.'},
      design:{name:'Graphic work',desc:'Create a futuristic campaign graphic.'},
      video:{name:'Video editing',desc:'Edit a technology showcase video.'},
      stream:{name:'Live stream',desc:'Broadcast a virtual tech event.'},
      consoleService:{name:'Console system check',desc:'Test and calibrate a refurbished console.'},
      vrService:{name:'VR optical calibration',desc:'Synchronize the display and motion sensors.'},
      racingService:{name:'Simulator setup',desc:'Calibrate the wheel, pedals, and force feedback.'}
    }
  }
};

const initial={balance:150000,xp:0,level:1,owned:[],cart:[],history:[],cooldowns:{},language:'hu'};
let state=load();let activeCategory='Mind';let search='';let timer=null;
function load(){try{return {...initial,...JSON.parse(localStorage.getItem('voltmarket-save')||'{}')}}catch{return {...initial}}}
function save(){localStorage.setItem('voltmarket-save',JSON.stringify(state));updateHud();applyLanguage()}
function fmt(n){return new Intl.NumberFormat(state.language==='en'?'en-US':'hu-HU').format(Math.round(n))}
function levelCap(){return state.level*100}
function updateLevel(){while(state.xp>=levelCap()){state.xp-=levelCap();state.level++;toast(getText('levelUp',{level:state.level}))}}
function bonus(){return products.filter(p=>state.owned.includes(p.id)).reduce((a,p)=>a+p.bonus,0)}
function cooldownCut(){return Math.min(.5,products.filter(p=>state.owned.includes(p.id)).reduce((a,p)=>a+p.cooldown,0))}
function speedBoost(){return products.filter(p=>state.owned.includes(p.id)).reduce((a,p)=>a+p.speedBoost,0)}
function xpBoost(){return products.filter(p=>state.owned.includes(p.id)).reduce((a,p)=>a+(p.xpBoost||0),0)}
function effectiveJobSeconds(job){return Math.max(3,Math.round(job.seconds*(1-Math.min(.65,cooldownCut()+speedBoost()))))}
function jobRun(id){const raw=state.cooldowns[id];if(!raw)return null;if(typeof raw==='number'){const job=jobs.find(j=>j.id===id),duration=effectiveJobSeconds(job);return {start:raw-duration*1000,end:raw,duration}}return raw}
function getText(key,replacements={}){const lang=translations[state.language]||translations.hu;let text=lang[key]||translations.hu[key]||key;Object.entries(replacements).forEach(([name,value])=>{text=text.replace(new RegExp(`\\{\\{${name}\\}\\}`,'g'),value)});return text}
function getProductMeta(id){const langProduct=(translations[state.language]||translations.hu).products?.[id]||translations.hu.products[id];const product=products.find(p=>p.id===id);return {name:langProduct?.name||product.name,cat:langProduct?.cat||product.cat,perk:langProduct?.perk||product.perk};}
function getJobMeta(id){const langJob=(translations[state.language]||translations.hu).jobs?.[id]||translations.hu.jobs[id];const job=jobs.find(j=>j.id===id);return {name:langJob?.name||job.name,desc:langJob?.desc||job.desc};}
function updateHud(){document.querySelector('#balance').textContent=fmt(state.balance);document.querySelector('#cartCount').textContent=state.cart.length;document.querySelector('#levelLabel').textContent=`${state.level}. ${state.language==='en'?'LEVEL':'SZINT'}`;document.querySelector('#xpText').textContent=`${state.xp} / ${levelCap()} XP`;document.querySelector('#xpBar').style.width=`${state.xp/levelCap()*100}%`;document.querySelector('#bonusText').textContent=`+${Math.round(bonus()*100)}% ${state.language==='en'?'revenue':'bevétel'}`}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='equipment')renderEquipment();if(id==='history')renderHistory();if(id==='jobs')renderJobs();window.scrollTo({top:0,behavior:'smooth'})}
function renderFilters(){const cats=['Mind',...new Set(products.map(p=>p.cat))];document.querySelector('#filters').innerHTML=cats.map(c=>`<button class="filter ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('')}
function renderProducts(){const list=products.filter(p=>(activeCategory==='Mind'||p.cat===activeCategory)&&p.name.toLowerCase().includes(search));document.querySelector('#productGrid').innerHTML=list.map(productCard).join('')||`<div class="empty-card">${getText('emptyProducts')}</div>`}
function applyLanguage(){const lang=translations[state.language]||translations.hu;document.documentElement.lang=state.language;document.body.dataset.language=state.language;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;el.textContent=lang[key]||el.textContent;});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const key=el.dataset.i18nPlaceholder;el.placeholder=lang[key]||el.placeholder;});const heroTitle=document.querySelector('#heroTitle');if(heroTitle)heroTitle.innerHTML=getText('heroTitle');const heroText=document.querySelector('#heroText');if(heroText)heroText.textContent=getText('heroText');const typingInput=document.querySelector('#typingInput');if(typingInput)typingInput.placeholder=getText('typingPlaceholder');const toggle=document.querySelector('#langToggle');if(toggle){toggle.textContent=state.language==='en'?'🇬🇧 EN':'🇭🇺 HU';toggle.setAttribute('aria-pressed',String(state.language==='en'));}const hud=document.querySelector('.hud');if(hud){hud.hidden=false;hud.removeAttribute('aria-hidden')}updateHud()}
function productCard(p){const owned=state.owned.includes(p.id),locked=state.level<p.level,inCart=state.cart.includes(p.id),meta=getProductMeta(p.id);return `<article class="product-card product-${p.id}">${owned?`<span class="owned-tag">${getText('ownedState')}</span>`:locked?`<span class="level-tag">${state.language==='en'?
`${p.level}. LEVEL`:`${p.level}. SZINT`}</span>`:''}<div class="product-visual product-art" aria-hidden="true"></div><div class="product-body"><span class="category">${meta.cat}</span><h3>${meta.name}</h3><p>${meta.perk}</p><div class="perk">${getText('activeEffect')} // ${meta.perk}</div><div class="product-foot"><span class="price">${fmt(p.price)} <small>CR</small></span><button class="small-btn add" data-id="${p.id}" ${owned||locked||inCart?'disabled':''}>${owned?getText('ownedState'):locked?getText('lockedState'):inCart?getText('inCartState'):getText('addToCart')}</button></div></div></article>`}
function renderEquipment(){const owned=products.filter(p=>state.owned.includes(p.id));document.querySelector('#equipmentGrid').innerHTML=owned.length?owned.map(productCard).join(''):`<div class="empty-card"><h3>${getText('emptyEquipmentTitle')}</h3><p>${getText('emptyEquipmentText')}</p></div>`}
function requirements(job){return state.level>=(job.level||1)&&job.requires.every(id=>state.owned.includes(id))}
function missingRequirements(job){const missing=job.requires.filter(id=>!state.owned.includes(id)).map(id=>getProductMeta(id).name);if(state.level<(job.level||1))missing.unshift(`${job.level}. szint`);return missing}
function renderJobs(){const now=Date.now();document.querySelector('#jobGrid').innerHTML=jobs.map(j=>{const req=requirements(j),run=jobRun(j.id),left=run?Math.max(0,Math.ceil((run.end-now)/1000)):0,meta=getJobMeta(j.id),missing=missingRequirements(j),effective=effectiveJobSeconds(j),xp=Math.round(j.xp*(1+xpBoost()));return `<article class="job-card ${req?'':'locked'}" data-job-id="${j.id}"><span class="job-icon">${j.icon}</span><h3>${meta.name}</h3><p>${meta.desc}</p><div class="job-meta"><span>${getText('jobReward')} <strong>${fmt(Math.round(j.reward*(1+bonus())))} CR</strong></span><span>+${xp} XP</span></div><small>${req?getText('jobReady'):`${getText('jobNeeds')} ${missing.join(', ')}`}</small><div class="time-breakdown">Alapidő: ${j.seconds} mp · Gyorsítás: -${j.seconds-effective} mp · Tényleges: ${effective} mp</div><div class="progress-mini"><div style="width:${run?Math.min(100,Math.max(0,(now-run.start)/(run.end-run.start)*100)):0}%"></div></div><button class="primary job-start" data-id="${j.id}" ${!req||left?'disabled':''}>${!req?getText('jobLocked'):left?`${getText('jobWait')} ${left} ${getText('jobSeconds')}`:getText('jobStart')}</button></article>`}).join('')}
function finishJob(id){const j=jobs.find(x=>x.id===id);if(!j||!state.cooldowns[id])return;const reward=Math.round(j.reward*(1+bonus()));state.balance+=reward;state.xp+=Math.round(j.xp*(1+xpBoost()));delete state.cooldowns[id];addHistory(j.name,reward);updateLevel();save();toast(`${j.name} kész: +${fmt(reward)} kredit`)}
function updateJobProgress(){const now=Date.now();Object.keys(state.cooldowns).forEach(id=>{const run=jobRun(id);if(run&&now>=run.end)finishJob(id)});document.querySelectorAll('#jobGrid .job-card').forEach(card=>{const id=card.dataset.jobId,j=jobs.find(x=>x.id===id);if(!j)return;const req=requirements(j),btn=card.querySelector('.job-start'),bar=card.querySelector('.progress-mini div'),run=jobRun(id);if(!req){btn.disabled=true;btn.textContent=getText('jobLocked');bar.style.width='0%';return}if(run&&now<run.end){const left=Math.max(0,Math.ceil((run.end-now)/1000));btn.disabled=true;btn.textContent=`${getText('jobWait')} ${left} ${getText('jobSeconds')}`;bar.style.width=`${Math.min(100,Math.max(0,(now-run.start)/(run.end-run.start)*100))}%`;return}btn.disabled=false;btn.textContent=getText('jobStart');bar.style.width='0%'})}
function renderHistory(){const el=document.querySelector('#historyList');el.innerHTML=state.history.length?state.history.map(h=>`<div class="history-row"><strong>${h.name}</strong><b class="${h.amount>=0?'positive':'negative'}">${h.amount>=0?'+':''}${fmt(h.amount)} CR</b><small>${h.time}</small></div>`).join(''):`<div class="empty-card">${getText('emptyHistory')}</div>`}
function renderCart(){const chosen=products.filter(p=>state.cart.includes(p.id));document.querySelector('#cartItems').innerHTML=chosen.length?chosen.map(p=>`<div class="cart-row"><span class="emoji">${p.icon}</span><div><strong>${getProductMeta(p.id).name}</strong><small>${fmt(p.price)} CR</small></div><button class="remove" data-id="${p.id}" aria-label="Eltávolítás">×</button></div>`).join(''):`<div class="empty-card">${getText('emptyCart')}</div>`;document.querySelector('#cartTotal').textContent=getText('cartTotalText',{amount:fmt(chosen.reduce((a,p)=>a+p.price,0))})}
function addHistory(name,amount){state.history.unshift({name,amount,time:new Date().toLocaleString('hu-HU')});state.history=state.history.slice(0,40)}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>el.classList.remove('show'),2600)}
function openCart(open=true){document.querySelector('#cartDrawer').classList.toggle('open',open);document.querySelector('#backdrop').classList.toggle('show',open);document.querySelector('#cartDrawer').setAttribute('aria-hidden',String(!open));if(open)renderCart()}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view){e.preventDefault();showView(view.dataset.view)}const filter=e.target.closest('[data-cat]');if(filter){activeCategory=filter.dataset.cat;renderFilters();renderProducts()}const add=e.target.closest('.add');if(add){state.cart.push(add.dataset.id);save();renderProducts();toast(getText('addToCartToast'))}const rem=e.target.closest('.remove');if(rem){state.cart=state.cart.filter(id=>id!==rem.dataset.id);save();renderCart();renderProducts()}const start=e.target.closest('.job-start');if(start)startJob(start.dataset.id)});
document.querySelector('#searchInput').addEventListener('input',e=>{search=e.target.value.trim().toLowerCase();renderProducts()});document.querySelector('#cartButton').onclick=()=>openCart();document.querySelector('#closeCart').onclick=()=>openCart(false);document.querySelector('#backdrop').onclick=()=>openCart(false);document.querySelector('#langToggle').addEventListener('click',()=>{state.language=state.language==='hu'?'en':'hu';localStorage.setItem('voltmarket-save',JSON.stringify(state));renderAll();requestAnimationFrame(()=>{document.querySelector('.hud')?.removeAttribute('hidden');updateHud()});toast(state.language==='en'?'Language switched to English':'Nyelv váltva magyarra');});
document.querySelector('#checkoutButton').onclick=()=>{const chosen=products.filter(p=>state.cart.includes(p.id)&&!state.owned.includes(p.id));const total=chosen.reduce((a,p)=>a+p.price,0);if(!chosen.length)return toast(getText('checkoutEmpty'));if(total>state.balance)return toast(getText('checkoutMissing',{amount:fmt(total-state.balance)}));state.balance-=total;state.owned.push(...chosen.map(p=>p.id));state.cart=[];addHistory(`${chosen.length} felszerelés vásárlása`,-total);save();renderProducts();renderCart();toast(getText('checkoutSuccess'))};
function startJob(id){const j=jobs.find(x=>x.id===id);if(!j||!requirements(j)||state.cooldowns[id])return;const seconds=effectiveJobSeconds(j),start=Date.now();state.cooldowns[id]={start,end:start+seconds*1000,duration:seconds};save();renderJobs()}
document.querySelector('#resetButton').onclick=()=>{if(confirm(getText('confirmReset'))){state={...initial,owned:[],cart:[],history:[],cooldowns:{}};save();renderAll();toast(getText('resetDone'))}};
function renderAll(){updateHud();renderFilters();renderProducts();renderJobs();renderEquipment();renderHistory();applyLanguage()}renderAll();setInterval(updateJobProgress,1000);updateJobProgress();
