const workshopParts=[
 {id:'battery',name:'Energiacella',icon:'🔋',price:18000},{id:'screen',name:'OLED kijelző',icon:'▣',price:22000},{id:'ssd',name:'NVMe tárhely',icon:'▤',price:14000},{id:'ram',name:'Memóriamodul',icon:'▥',price:18000},{id:'cpu',name:'Processzor',icon:'▦',price:35000},{id:'gpu',name:'Grafikus kártya',icon:'▰',price:65000},{id:'case',name:'Gépház és táp',icon:'▧',price:25000},
 {id:'consolePower',name:'Konzol tápegység',icon:'⚡',price:26000},{id:'consoleFan',name:'Konzol ventilátor',icon:'❄',price:21000},{id:'hdmi',name:'HDMI modul',icon:'▱',price:19000},{id:'vrDisplay',name:'VR kijelzőmodul',icon:'◉',price:42000},{id:'motion',name:'Mozgásérzékelő',icon:'⌁',price:31000},{id:'lens',name:'Optikai lencsepár',icon:'◌',price:28000},{id:'wheelMotor',name:'Force feedback motor',icon:'⚙',price:38000},{id:'pedal',name:'Pedálszenzor',icon:'⌄',price:24000},{id:'usb',name:'USB vezérlőpanel',icon:'⌘',price:18000}
];
const qualities={used:{name:'Használt',price:.65,sell:.85,xp:0},normal:{name:'Normál',price:1,sell:1,xp:0},premium:{name:'Prémium',price:1.55,sell:1.25,xp:.1}};
const blueprints=[
 {id:'phonefix',name:'Hibás Nova telefon',icon:'📱',buy:8000,sell:65000,parts:['screen','battery'],fault:'Betört kijelző és gyenge akkumulátor.',level:1},
 {id:'laptopfix',name:'Hibás Pulse laptop',icon:'💻',buy:18000,sell:92000,parts:['ssd','battery','ram'],fault:'Lassú tárhely és instabil memória.',level:3},
 {id:'pcbuild',name:'Egyedi gamer PC',icon:'🖥️',buy:15000,sell:230000,parts:['case','cpu','ram','ssd','gpu'],fault:'Építs teljes gépet válogatott alkatrészekből.',level:5},
 {id:'consolefix',name:'Hibás játékkonzol',icon:'🎮',buy:42000,sell:175000,parts:['consolePower','consoleFan','hdmi','ssd'],fault:'Tápellátási és hűtési hibák.',level:10,gear:'consoleStation'},
 {id:'vrfix',name:'Hibás VR-szemüveg',icon:'🥽',buy:52000,sell:225000,parts:['vrDisplay','motion','lens','battery'],fault:'Pontatlan követés és kijelzőhiba.',level:10,gear:'vrToolkit'},
 {id:'racingfix',name:'Hibás játékkormány',icon:'🏎️',buy:46000,sell:195000,parts:['wheelMotor','pedal','usb'],fault:'Gyenge visszacsatolás és hibás pedál.',level:10,gear:'racingRig'}
];
const codes=['SCAN-DEVICE','CHECK-POWER','MEMORY-TEST','DISPLAY-LINK','STORAGE-OK','THERMAL-SCAN'];
const emptyWorkshop={parts:{},projects:[],finished:[],nextId:1,wheelReadyAt:0,wheelSpins:0};
let workshop=loadWorkshop(),game={mode:null,projectId:null,index:0,sequence:[]},wheelBusy=false;
function migrateParts(parts={}){const result={};Object.entries(parts).forEach(([id,value])=>{result[id]=typeof value==='number'?{used:0,normal:value,premium:0}:{used:0,normal:0,premium:0,...value}});return result}
function loadWorkshop(){try{const saved=JSON.parse(localStorage.getItem('voltmarket-workshop')||'{}');return {...emptyWorkshop,...saved,parts:migrateParts(saved.parts),projects:saved.projects||[],finished:saved.finished||[]}}catch{return {...emptyWorkshop,parts:{},projects:[],finished:[]}}}
function saveWorkshop(){localStorage.setItem('voltmarket-workshop',JSON.stringify(workshop));renderWorkshop();updateWheel()}
function stock(id,q='normal'){return workshop.parts[id]?.[q]||0}
function ensurePart(id){workshop.parts[id]??={used:0,normal:0,premium:0};return workshop.parts[id]}
function partName(id){return workshopParts.find(p=>p.id===id)?.name||id}
function projectByUid(uid){return workshop.projects.find(p=>p.uid===Number(uid))}
function blueprint(id){return blueprints.find(b=>b.id===id)}
function blueprintAccess(b){return state.level>=b.level&&(!b.gear||state.owned.includes(b.gear))}
function accessText(b){const missing=[];if(state.level<b.level)missing.push(`${b.level}. szint`);if(b.gear&&!state.owned.includes(b.gear))missing.push(getProductMeta(b.gear).name);return missing.join(' + ')}
function renderWorkshop(){
 const partTotal=Object.values(workshop.parts).reduce((sum,group)=>sum+Object.values(group).reduce((a,b)=>a+b,0),0);
 document.querySelector('#partCount').textContent=`${partTotal} db`;document.querySelector('#projectCount').textContent=`${workshop.projects.length} projekt`;document.querySelector('#finishedCount').textContent=`${workshop.finished.length} eszköz`;
 document.querySelector('#salvageGrid').innerHTML=blueprints.map(b=>{const open=blueprintAccess(b);return `<article class="salvage-card ${open?'':'locked-card'}"><div class="salvage-top"><span class="device-icon">${b.icon}</span><div><h3>${b.name}</h3><span class="category">${open?`VÁRHATÓ ELADÁS: ${fmt(b.sell)} CR`:`🔒 ${accessText(b)}`}</span></div></div><p>${b.fault}</p><div class="trade-row"><strong>${fmt(b.buy)} CR</strong><button class="small-btn salvage-buy" data-blueprint="${b.id}" ${open?'':'disabled'}>${open?'Projekt megvétele':'Zárolva'}</button></div></article>`}).join('');
 document.querySelector('#partsGrid').innerHTML=workshopParts.map(p=>`<article class="part-card"><div class="part-top"><span class="part-icon">${p.icon}</span><div><h3>${p.name}</h3><span class="category">H ${stock(p.id,'used')} · N ${stock(p.id)} · P ${stock(p.id,'premium')}</span></div></div><div class="quality-shop">${Object.entries(qualities).map(([q,v])=>`<button class="quality-buy ${q}" data-part="${p.id}" data-quality="${q}"><span>${v.name}</span><strong>${fmt(p.price*v.price)} CR</strong></button>`).join('')}</div></article>`).join('');
 document.querySelector('#projectGrid').innerHTML=workshop.projects.length?workshop.projects.map(renderProject).join(''):'<div class="empty-card">Nincs aktív projekt. Vegyél egy hibás eszközt a készletből.</div>';
 document.querySelector('#finishedGrid').innerHTML=workshop.finished.length?workshop.finished.map((f,i)=>{const b=blueprint(f.type),q=qualities[f.quality||'normal'],sell=Math.round(b.sell*q.sell);return `<article class="finished-card"><span class="device-icon">${b.icon}</span><span class="project-stage">${q.name.toUpperCase()} // KÉSZ</span><h3>${b.name}</h3><span class="profit">${fmt(sell)} CR</span><button class="primary sell-device" data-finished="${i}">Eladás</button></article>`}).join(''):'<div class="empty-card">A megjavított eszközök itt várják majd az eladást.</div>';
}
function renderProject(p){const b=blueprint(p.type),q=p.quality||'normal',ready=b.parts.every(id=>stock(id,q)>0),open=blueprintAccess(b);return `<article class="project-card ${open?'':'locked-card'}"><span class="project-stage">${p.diagnosed?'ALKATRÉSZEKRE VÁR':'DIAGNOSZTIKA'}</span><h3>${b.icon} ${b.name}</h3><p>${open?(p.diagnosed?'Válassz minőséget, majd szereld össze.':'Egyetlen diagnosztikai feladat szükséges.'):`🔒 ${accessText(b)}`}</p><div class="quality-tabs">${Object.entries(qualities).map(([id,v])=>`<button class="quality-select ${q===id?'active':''}" data-project="${p.uid}" data-project-quality="${id}" ${p.diagnosed&&open?'':'disabled'}>${v.name}</button>`).join('')}</div><div class="needs">${b.parts.map(id=>`<b class="${stock(id,q)>0?'have':''}">${partName(id)} ${stock(id,q)>0?'✓':'×'}</b>`).join('')}</div><button class="primary ${p.diagnosed?'assemble':'diagnose'}" data-project="${p.uid}" ${!open||(p.diagnosed&&!ready)?'disabled':''}>${!open?'Zárolva':p.diagnosed?(ready?'Összeszerelés indítása':'Hiányzó alkatrész'):'Diagnosztika indítása'}</button></article>`}
function buySalvage(type){const b=blueprint(type);if(!blueprintAccess(b))return toast(`Még hiányzik: ${accessText(b)}`);if(state.balance<b.buy)return toast('Nincs elég kredited ehhez a projekthez.');state.balance-=b.buy;workshop.projects.push({uid:workshop.nextId++,type,diagnosed:false,quality:'normal'});addHistory(`Hibás eszköz: ${b.name}`,-b.buy);save();saveWorkshop();toast('A hibás eszköz a munkapadra került.')}
function buyPart(id,q){const p=workshopParts.find(x=>x.id===id),quality=qualities[q],price=Math.round(p.price*quality.price);if(state.balance<price)return toast('Nincs elég kredited az alkatrészhez.');state.balance-=price;ensurePart(id)[q]++;addHistory(`${quality.name} ${p.name}`,-price);save();saveWorkshop();toast(`${quality.name} ${p.name} megvásárolva.`)}
function setProjectQuality(uid,q){const p=projectByUid(uid);if(p&&qualities[q]){p.quality=q;saveWorkshop()}}
function openGame(){document.querySelector('#gameModal').classList.add('open');document.querySelector('#gameModal').setAttribute('aria-hidden','false')}
function closeGame(){document.querySelector('#gameModal').classList.remove('open');document.querySelector('#gameModal').setAttribute('aria-hidden','true');document.querySelector('#typingInput').style.display='block';document.querySelector('#typingInput').value='';document.querySelector('.game-box p').textContent='Teljesítsd az egyszeri diagnosztikai feladatot.';document.querySelectorAll('.assembly-options').forEach(x=>x.remove());game.mode=null}
function startDiagnostic(uid){const p=projectByUid(uid);if(!p||p.diagnosed)return;game={mode:'typing',projectId:Number(uid),index:0,sequence:[]};openGame();document.querySelector('.game-box p').textContent='Írd be egyszer pontosan a megjelenő hibakódot.';document.querySelector('#typingInput').style.display='block';document.querySelector('#targetText').textContent=codes[Math.floor(Math.random()*codes.length)]+`-${Math.floor(100+Math.random()*900)}`;document.querySelector('#gameProgress').textContent='0 / 1';document.querySelector('#gameTimer').textContent='EGYSZERI ELLENŐRZÉS';document.querySelector('#typingInput').focus()}
function typingInput(e){if(game.mode!=='typing')return;if(e.target.value.trim().toUpperCase()===document.querySelector('#targetText').textContent){const p=projectByUid(game.projectId);p.diagnosed=true;state.xp+=25;updateLevel();save();saveWorkshop();closeGame();toast('Diagnosztika sikeres: +25 XP')}}
function startAssembly(uid){const p=projectByUid(uid),b=blueprint(p.type),q=p.quality||'normal';if(!b.parts.every(id=>stock(id,q)>0))return;game={mode:'assembly',projectId:Number(uid),index:0,sequence:[...b.parts]};openGame();document.querySelector('.game-box p').textContent='Szereld be az alkatrészeket a kijelzett sorrendben.';document.querySelector('#typingInput').style.display='none';document.querySelector('#targetText').textContent=`Következő: ${partName(game.sequence[0])}`;document.querySelector('#gameTimer').textContent='PONTOS SORREND';document.querySelector('#gameProgress').textContent=`0 / ${game.sequence.length}`;const opts=document.createElement('div');opts.className='assembly-options filters';opts.innerHTML=[...b.parts].sort(()=>Math.random()-.5).map(id=>`<button class="filter assembly-part" data-assembly-part="${id}">${partName(id)}</button>`).join('');document.querySelector('#targetText').after(opts)}
function chooseAssembly(id){if(game.mode!=='assembly')return;if(id!==game.sequence[game.index]){game.index=0;document.querySelector('#gameProgress').textContent=`0 / ${game.sequence.length}`;document.querySelector('#targetText').textContent=`Hibás sorrend! Kezdd újra: ${partName(game.sequence[0])}`;return}game.index++;document.querySelector('#gameProgress').textContent=`${game.index} / ${game.sequence.length}`;if(game.index===game.sequence.length)return finishAssembly();document.querySelector('#targetText').textContent=`Következő: ${partName(game.sequence[game.index])}`}
function finishAssembly(){const p=projectByUid(game.projectId),b=blueprint(p.type),q=p.quality||'normal';b.parts.forEach(id=>ensurePart(id)[q]--);workshop.projects=workshop.projects.filter(x=>x.uid!==p.uid);workshop.finished.push({type:p.type,quality:q,completed:Date.now()});state.xp+=Math.round(45*(1+qualities[q].xp));updateLevel();save();saveWorkshop();closeGame();toast('Sikeres összeszerelés: az eszköz eladható.')}
function sellFinished(index){const item=workshop.finished[index],b=blueprint(item.type),q=qualities[item.quality||'normal'],value=Math.round(b.sell*q.sell);state.balance+=value;state.xp+=20;updateLevel();addHistory(`Eladás: ${b.name}`,value);workshop.finished.splice(index,1);save();saveWorkshop();toast(`Eladva: +${fmt(value)} kredit`)}
const wheelRewards=[
 {label:'2 000 kredit',weight:22,run:()=>{state.balance+=2000;addHistory('Tech kerék jutalom',2000)}},{label:'5 000 kredit',weight:10,run:()=>{state.balance+=5000;addHistory('Tech kerék jutalom',5000)}},{label:'+30 XP',weight:16,run:()=>{state.xp+=30;updateLevel()}},{label:'Használt alkatrész',weight:18,run:()=>giveRandomPart('used')},{label:'Normál alkatrész',weight:14,run:()=>giveRandomPart('normal')},{label:'Prémium alkatrész',weight:5,run:()=>giveRandomPart('premium')},{label:'Hibás eszköz',weight:8,run:giveBrokenDevice},{label:'Javított telefon',weight:3,run:()=>workshop.finished.push({type:'phonefix',quality:'used',completed:Date.now()})},{label:'Most nincs jutalom',weight:4,run:()=>{}}
];
function giveRandomPart(q){const advanced=['consolePower','consoleFan','hdmi','vrDisplay','motion','lens','wheelMotor','pedal','usb'],pool=workshopParts.filter(p=>state.level>=10||!advanced.includes(p.id)),part=pool[Math.floor(Math.random()*pool.length)];ensurePart(part.id)[q]++}
function giveBrokenDevice(){const pool=blueprints.filter(blueprintAccess),b=pool[Math.floor(Math.random()*pool.length)]||blueprints[0];workshop.projects.push({uid:workshop.nextId++,type:b.id,diagnosed:false,quality:'normal'})}
function weightedReward(){let roll=Math.random()*wheelRewards.reduce((a,r)=>a+r.weight,0);return wheelRewards.find(r=>(roll-=r.weight)<=0)||wheelRewards[0]}
function updateWheel(){const button=document.querySelector('#spinWheel'),label=document.querySelector('#wheelCooldown');if(!button||wheelBusy)return;const left=Math.max(0,workshop.wheelReadyAt-Date.now());button.disabled=left>0;if(left>0){const total=Math.ceil(left/1000),m=String(Math.floor(total/60)).padStart(2,'0'),s=String(total%60).padStart(2,'0');label.textContent=`Következő pörgetés: ${m}:${s}`}else label.textContent='Pörgetésre kész'}
function spinWheel(){if(wheelBusy||Date.now()<workshop.wheelReadyAt)return;wheelBusy=true;const wheel=document.querySelector('#prizeWheel'),button=document.querySelector('#spinWheel'),result=weightedReward(),turn=1440+Math.floor(Math.random()*360);button.disabled=true;document.querySelector('#wheelResult').textContent='A kerék forog…';wheel.style.setProperty('--wheel-turn',`${turn}deg`);wheel.classList.remove('spinning');void wheel.offsetWidth;wheel.classList.add('spinning');setTimeout(()=>{result.run();workshop.wheelReadyAt=Date.now()+600000;workshop.wheelSpins++;wheelBusy=false;save();saveWorkshop();document.querySelector('#wheelResult').textContent=`Jutalmad: ${result.label}`;toast(`Tech kerék: ${result.label}`)},4200)}
document.addEventListener('click',e=>{if(e.target.closest('[data-view="workshop"]'))renderWorkshop();const salvage=e.target.closest('.salvage-buy');if(salvage)buySalvage(salvage.dataset.blueprint);const part=e.target.closest('.quality-buy');if(part)buyPart(part.dataset.part,part.dataset.quality);const quality=e.target.closest('.quality-select');if(quality)setProjectQuality(quality.dataset.project,quality.dataset.projectQuality);const diagnose=e.target.closest('.diagnose');if(diagnose)startDiagnostic(diagnose.dataset.project);const assemble=e.target.closest('.assemble');if(assemble)startAssembly(assemble.dataset.project);const piece=e.target.closest('.assembly-part');if(piece)chooseAssembly(piece.dataset.assemblyPart);const sell=e.target.closest('.sell-device');if(sell)sellFinished(Number(sell.dataset.finished))});
document.querySelector('#typingInput').addEventListener('input',typingInput);document.querySelector('#closeGame').onclick=closeGame;document.querySelector('#gameModal').addEventListener('click',e=>{if(e.target.id==='gameModal')closeGame()});document.querySelector('#spinWheel').addEventListener('click',spinWheel);document.querySelector('#resetButton').addEventListener('click',()=>{setTimeout(()=>{if(state.balance===150000&&state.level===1&&state.history.length===0){workshop={...emptyWorkshop,parts:{},projects:[],finished:[],nextId:1};saveWorkshop()}},0)});setInterval(updateWheel,1000);updateWheel();renderWorkshop();
